version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      # Mount the source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      # Mount these separately to prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true  # Enable polling for hot reload in Docker
    stdin_open: true  # Keep STDIN open for React DevTools
    tty: true        # Allocate a pseudo-TTY 