version: '3.8'

services:
  foy:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: foy_dev_app
    ports:
      - "5173:5173"
    volumes:
      # Mount the source code for hot reload
      - ./src:/app/src
      - ./public:/app/public
      # Mount these separately to prevent node_modules from being overwritten
      - /app/node_modules
    environment:
      - NODE_ENV=development
      